FunctionNaming:
  active: true
  excludes: [
    '**/test/**',
    '**/androidTest/**',
    '**/commonTest/**',
    '**/jvmTest/**',
    '**/androidUnitTest/**',
    '**/androidInstrumentedTest/**',
    '**/jsTest/**',
    '**/iosTest/**'
  ]
  functionPattern: '[a-z][a-zA-Z0-9]*'
  excludeClassPattern: '$^'
  ignoreAnnotated: [ 'Composable' ]

LongMethod:
  active: true
  threshold: 40

LongParameterList:
  active: true
  functionThreshold: 8

ComplexCondition:
  active: true
  threshold: 4